In [ ]:
!pip install openpyxl

In [ ]:
# Data Cleaning Project - Customers, Orders, Products

## Task 1: Load Files
## Task 2: Inspect Data (head, info, isnull)
## Task 3: Clean Text Columns (whitespace, standardize)
## Task 4: Convert to Numeric
## Task 5: Convert to Datetime
## Task 6: Handle Missing Values with fillna() + Reasons
## Task 7: Check Duplicates & Primary Keys
## Task 8: Validate Positive Quantity & Non-Negative Amount
## Task 9 & 10: Merge & Final Table
## Task 11: Export Cleaned Data
## Task 12: Data Quality Report

## Conclusion

In [2]:
import pandas as pd

In [3]:
customers = pd.read_csv("customers.csv")

In [4]:
orders = pd.read_json("orders.json")

In [5]:
products = pd.read_excel("products.xlsx")

In [33]:
print(customers.head())

   customer_id customer_name                      email       city signup_date
0         1001    Arun Kumar    arun.kumar1@example.com      Delhi  2026-05-06
1         1002     Nila Nair     nila.nair2@example.com  Bengaluru  2026-02-14
2         1003  Deepak Patel  deepak.patel3@example.com    Chennai  2026-01-16
3         1004     Meena Ali     meena.ali4@example.com     Mumbai  2026-09-16
4         1005   Pooja Kumar   pooja.kumar5@example.com     Mumbai  2026-08-03

In [7]:
print(orders.head())

  order_id  customer_id product_id quantity order_amount  order_date  \
0  ORD0001         1036      PR099        5      6973.75  2026-08-02
1  ORD0002         1010      PR092        3      8495.81  2026-07-01
2  ORD0003         1070      PR011        2      9668.43  2026-06-20
3  ORD0004         1020      PR091        2     10278.84  2026-06-09
4  ORD0005         1070      PR060        4     20847.35  2026-06-08

  order_status
0      Shipped
1      Pending
2      Shipped
3    Cancelled
4      Shipped

In [8]:
print(products.head())

  product_id         product_name     category unit_price
0      PR001  Wireless Headphones  Electronics    5846.84
1      PR002             Keyboard  Electronics    9836.15
2      PR003          Smart Watch  Electronics     477.75
3      PR004         Office Chair    Furniture    6005.06
4      PR005          USB-C Cable  Accessories     3521.3

In [101]:
print(customers.info())

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    100 non-null    int64
 1   customer_name  100 non-null    str
 2   email          96 non-null     str
 3   city           95 non-null     str
 4   signup_date    100 non-null    datetime64[us]
dtypes: datetime64[us](1), int64(1), str(3)
memory usage: 4.0 KB
None

In [102]:
print(orders.info())

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      100 non-null    str
 1   customer_id   100 non-null    int64
 2   product_id    100 non-null    str
 3   quantity      100 non-null    int64
 4   order_amount  100 non-null    float64
 5   order_date    95 non-null     datetime64[us]
 6   order_status  96 non-null     string
dtypes: datetime64[us](1), float64(1), int64(2), str(2), string(1)
memory usage: 5.6 KB
None

In [103]:
print(products.info())

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    100 non-null    str
 1   product_name  100 non-null    str
 2   category      100 non-null    str
 3   unit_price    94 non-null     float64
dtypes: float64(1), str(3)
memory usage: 3.3 KB
None

In [86]:
print(customers.isnull().sum())

customer_id      0
customer_name    0
email            4
city             5
signup_date      0
dtype: int64

In [87]:
print(orders.isnull().sum())

order_id        0
customer_id     0
product_id      0
quantity        0
order_amount    0
order_date      5
order_status    4
dtype: int64

In [88]:
print(products.isnull().sum())

product_id      0
product_name    0
category        0
unit_price      3
dtype: int64

In [89]:
customers.dtypes

customer_id               int64
customer_name               str
email                       str
city                        str
signup_date      datetime64[us]
dtype: object

In [90]:
orders.dtypes

order_id                   str
customer_id              int64
product_id                 str
quantity                 int64
order_amount           float64
order_date      datetime64[us]
order_status            string
dtype: object

In [91]:
products.dtypes

product_id      str
product_name    str
category        str
unit_price      str
dtype: object

In [ ]:
TASK 3 - Text Cleaning (Your first cleaning)
What: Make all text same format
How:
customer_name: str.strip() to remove spaces + str.title() for proper name
email: str.strip() + str.lower() - all emails lower casecity: str.strip() + str.title() - so KOLKATA -> Kolkata
category: str.strip() + str.lower() or str.title() - so all electronics same
order_status: str.strip() + str.title() - so cancelled -> Cancelled

## TEXT CLEANING

In [31]:
# CUSTOMERS

customers["customer_name"] = customers["customer_name"].str.strip().str.title()

In [34]:
customers["email"] = customers["email"].str.strip().str.lower()

In [37]:
orders["order_status"] = orders["order_status"].str.strip().str.title()

In [36]:
products["category"] = products["category"].str.strip().str.title()

In [43]:
customers["city"] = customers["city"].str.title()

In [46]:
print(customers["city"].unique())

<StringArray>
[    'Delhi', 'Bengaluru',   'Chennai',    'Mumbai',     'Kochi',         nan,
 'Hyderabad',   'Kolkata',      'Pune']
Length: 9, dtype: str

In [45]:
customers.head(100)

,customer_id,customer_name,email,city,signup_date
0,1001,Arun Kumar,arun.kumar1@example.com,Delhi,2026-05-06
1,1002,Nila Nair,nila.nair2@example.com,Bengaluru,2026-02-14
2,1003,Deepak Patel,deepak.patel3@example.com,Chennai,2026-01-16
3,1004,Meena Ali,meena.ali4@example.com,Mumbai,2026-09-16
4,1005,Pooja Kumar,pooja.kumar5@example.com,Mumbai,2026-08-03
...,...,...,...,...,...
95,1096,Sara Reddy,sara.reddy96@example.com,Kochi,2026-06-06
96,1097,Nila Joseph,nila.joseph97@example.com,Chennai,2026-04-09
97,1098,Karthik Rao,karthik.rao98@example.com,Delhi,2026-02-05
98,1099,Vikram Menon,vikram.menon99@example.com,Pune,2026-06-19
99,1100,Asha Prakash,asha.prakash100@example.com,Delhi,2026-04-02

In [64]:
orders.head(25)

,order_id,customer_id,product_id,quantity,order_amount,order_date,order_status
0,ORD0001,1036,PR099,5,6973.75,2026-08-02,Shipped
1,ORD0002,1010,PR092,3,8495.81,2026-07-01,Pending
2,ORD0003,1070,PR011,2,9668.43,2026-06-20,Shipped
3,ORD0004,1020,PR091,2,10278.84,2026-06-09,Cancelled
4,ORD0005,1070,PR060,4,20847.35,2026-06-08,Shipped
5,ORD0006,1050,PR099,5,21439.79,2026-08-29,Delivered
6,ORD0007,1098,PR074,4,23577.13,2026-08-01,Delivered
7,ORD0008,1039,PR097,4,13524.78,2026-09-18,Cancelled
8,ORD0009,1095,PR070,5,12282.5,2026-09-23,Shipped
9,ORD0010,1035,PR056,4,8502.82,2026-06-04,Cancelled
10,ORD0011,1087,PR052,2,23000.61,2026-09-16,Cancelled
11,ORD0012,1080,PR069,1,14858.54,2026-09-25,Cancelled
12,ORD0013,1085,PR004,1,3522.13,2026-08-22,Cancelled
13,ORD0014,1060,PR024,1,8284.71,2026-07-04,Cancelled
14,ORD0015,1059,PR042,3,7064.68,2026-09-06,Cancelled
15,ORD0016,1054,PR033,3,18763.25,2026-07-31,Delivered
16,ORD0017,1007,PR045,2,19563.64,2026-08-23,Delivered
17,ORD0018,1084,PR006,1,21004.84,not known,Shipped
18,ORD0019,1080,PR020,2,16786.05,2026-06-17,Cancelled
19,ORD0020,9999,PR028,4,19207.42,2026-08-29,Pending
20,ORD0021,1022,PR078,0,19478.13,2026-09-04,Delivered
21,ORD0022,1021,PR040,1,23232.85,2026-08-14,NaN
22,ORD0023,1074,PR087,4,2038.51,2026-07-21,Shipped
23,ORD0024,1089,PR999,2,21279.79,2026-06-14,Pending
24,ORD0025,1077,PR016,5,N/A,2026-09-09,Delivered

In [42]:
products.head(20)

   product_id         product_name     category unit_price
0       PR001  Wireless Headphones  Electronics    5846.84
1       PR002             Keyboard  Electronics    9836.15
2       PR003          Smart Watch  Electronics     477.75
3       PR004         Office Chair    Furniture    6005.06
4       PR005          USB-C Cable  Accessories     3521.3
5       PR006               Webcam  Electronics    7884.64
6       PR007            Desk Lamp         Home     4419.3
7       PR008         Laptop Stand  Accessories    9842.93
8       PR009         Water Bottle    Lifestyle    1243.89
9       PR010    Bluetooth Speaker  Electronics     9004.1
10      PR011         Notebook Set   Stationery    1980.78
11      PR012              Monitor  Electronics     538.43
12      PR013             Backpack    Lifestyle    4415.97
13      PR014                Mouse  Electronics    5246.21
14      PR015           Phone Case  Accessories    8083.46
15      PR016            Table Fan         Home    6898.89
16      PR017           Power Bank  Electronics     9407.6
17      PR018          Study Table    Furniture    7395.67
18      PR019              Pen Set   Stationery    2049.65
19      PR020           Travel Mug    Lifestyle    4368.84

In [47]:
print(products["product_name"].unique())

<StringArray>
[        'Wireless Headphones',                    'Keyboard',
                 'Smart Watch',                'Office Chair',
                 'USB-C Cable',                      'Webcam',
                   'Desk Lamp',                'Laptop Stand',
                'Water Bottle',           'Bluetooth Speaker',
                'Notebook Set',                     'Monitor',
                    'Backpack',                       'Mouse',
                  'Phone Case',                   'Table Fan',
                  'Power Bank',                 'Study Table',
                     'Pen Set',                  'Travel Mug',
 'Wireless Headphones Model 2',            'Keyboard Model 2',
         'Smart Watch Model 2',        'Office Chair Model 2',
         'USB-C Cable Model 2',              'Webcam Model 2',
           'Desk Lamp Model 2',        'Laptop Stand Model 2',
        'Water Bottle Model 2',   'Bluetooth Speaker Model 2',
        'Notebook Set Model 2',             'Monitor Model 2',
            'Backpack Model 2',               'Mouse Model 2',
          'Phone Case Model 2',           'Table Fan Model 2',
          'Power Bank Model 2',         'Study Table Model 2',
             'Pen Set Model 2',          'Travel Mug Model 2',
 'Wireless Headphones Model 3',            'Keyboard Model 3',
         'Smart Watch Model 3',        'Office Chair Model 3',
         'USB-C Cable Model 3',              'Webcam Model 3',
           'Desk Lamp Model 3',        'Laptop Stand Model 3',
        'Water Bottle Model 3',   'Bluetooth Speaker Model 3',
        'Notebook Set Model 3',             'Monitor Model 3',
            'Backpack Model 3',               'Mouse Model 3',
          'Phone Case Model 3',           'Table Fan Model 3',
          'Power Bank Model 3',         'Study Table Model 3',
             'Pen Set Model 3',          'Travel Mug Model 3',
 'Wireless Headphones Model 4',            'Keyboard Model 4',
         'Smart Watch Model 4',        'Office Chair Model 4',
         'USB-C Cable Model 4',              'Webcam Model 4',
           'Desk Lamp Model 4',        'Laptop Stand Model 4',
        'Water Bottle Model 4',   'Bluetooth Speaker Model 4',
        'Notebook Set Model 4',             'Monitor Model 4',
            'Backpack Model 4',               'Mouse Model 4',
          'Phone Case Model 4',           'Table Fan Model 4',
          'Power Bank Model 4',         'Study Table Model 4',
             'Pen Set Model 4',          'Travel Mug Model 4',
 'Wireless Headphones Model 5',            'Keyboard Model 5',
         'Smart Watch Model 5',        'Office Chair Model 5',
         'USB-C Cable Model 5',              'Webcam Model 5',
           'Desk Lamp Model 5',        'Laptop Stand Model 5',
        'Water Bottle Model 5',   'Bluetooth Speaker Model 5',
        'Notebook Set Model 5',             'Monitor Model 5',
            'Backpack Model 5',               'Mouse Model 5',
          'Phone Case Model 5',           'Table Fan Model 5',
          'Power Bank Model 5',         'Study Table Model 5',
             'Pen Set Model 5',          'Travel Mug Model 5']
Length: 100, dtype: str

## CONVERSION

In [48]:
customers['signup_date'] = pd.to_datetime(customers['signup_date'])

In [57]:
orders["quantity"] = orders["quantity"].replace("three",3)

In [60]:
orders['quantity'] = pd.to_numeric(orders['quantity'])

In [65]:
orders["order_amount"] = pd.to_numeric(orders["order_amount"], errors = "coerce")

In [66]:
print(orders["quantity"].unique())

[ 5  3  2  4  1  0 -2]

In [67]:
orders["order_amount"] = pd.to_numeric(orders["order_amount"], errors="coerce")

In [80]:
print(orders["order_date"].unique())

<DatetimeArray>
['2026-08-02 00:00:00', '2026-07-01 00:00:00', '2026-06-20 00:00:00',
 '2026-06-09 00:00:00', '2026-06-08 00:00:00', '2026-08-29 00:00:00',
 '2026-08-01 00:00:00', '2026-09-18 00:00:00', '2026-09-23 00:00:00',
 '2026-06-04 00:00:00', '2026-09-16 00:00:00', '2026-09-25 00:00:00',
 '2026-08-22 00:00:00', '2026-07-04 00:00:00', '2026-09-06 00:00:00',
 '2026-07-31 00:00:00', '2026-08-23 00:00:00',                 'NaT',
 '2026-06-17 00:00:00', '2026-09-04 00:00:00', '2026-08-14 00:00:00',
 '2026-07-21 00:00:00', '2026-06-14 00:00:00', '2026-09-09 00:00:00',
 '2026-07-26 00:00:00', '2026-09-12 00:00:00', '2026-07-12 00:00:00',
 '2026-07-02 00:00:00', '2026-07-16 00:00:00', '2026-08-11 00:00:00',
 '2026-09-01 00:00:00', '2026-06-29 00:00:00', '2026-07-18 00:00:00',
 '2026-07-13 00:00:00', '2026-06-30 00:00:00', '2026-07-17 00:00:00',
 '2026-07-06 00:00:00', '2026-08-21 00:00:00', '2026-09-29 00:00:00',
 '2026-06-10 00:00:00', '2026-09-10 00:00:00', '2026-07-09 00:00:00',
 '2026-09-03 00:00:00', '2026-07-08 00:00:00', '2026-07-25 00:00:00',
 '2026-09-14 00:00:00', '2026-07-27 00:00:00', '2026-08-17 00:00:00',
 '2026-08-15 00:00:00', '2026-06-06 00:00:00', '2026-06-24 00:00:00',
 '2026-07-15 00:00:00', '2026-09-13 00:00:00', '2026-06-15 00:00:00',
 '2026-07-30 00:00:00', '2026-09-05 00:00:00', '2026-06-16 00:00:00',
 '2026-07-10 00:00:00', '2026-08-05 00:00:00', '2026-07-29 00:00:00',
 '2026-09-19 00:00:00', '2026-07-05 00:00:00', '2026-08-24 00:00:00',
 '2026-09-28 00:00:00', '2026-07-20 00:00:00', '2026-08-03 00:00:00',
 '2026-09-20 00:00:00', '2026-07-23 00:00:00', '2026-08-28 00:00:00',
 '2026-07-19 00:00:00', '2026-06-11 00:00:00', '2026-06-19 00:00:00',
 '2026-08-25 00:00:00', '2026-06-21 00:00:00']
Length: 74, dtype: datetime64[us]

In [69]:
import numpy as np

In [70]:
orders.loc[orders['order_amount'] < 0, 'order_amount'] = np.nan

In [71]:
orders["order_amount"] = orders["order_amount"].fillna(orders["order_amount"].median())

In [74]:
orders["order_amount"] = orders["order_amount"].astype(float)

In [79]:
orders["order_date"] = pd.to_datetime(orders["order_date"], errors = "coerce")

In [81]:
print(orders["order_status"])

0       Shipped
1       Pending
2       Shipped
3     Cancelled
4       Shipped
        ...
95      Shipped
96    Delivered
97    Delivered
98    Cancelled
99    Cancelled
Name: order_status, Length: 100, dtype: str

In [82]:
orders.head(30)

,order_id,customer_id,product_id,quantity,order_amount,order_date,order_status
0,ORD0001,1036,PR099,5,6973.75,2026-08-02,Shipped
1,ORD0002,1010,PR092,3,8495.81,2026-07-01,Pending
2,ORD0003,1070,PR011,2,9668.43,2026-06-20,Shipped
3,ORD0004,1020,PR091,2,10278.84,2026-06-09,Cancelled
4,ORD0005,1070,PR060,4,20847.35,2026-06-08,Shipped
5,ORD0006,1050,PR099,5,21439.79,2026-08-29,Delivered
6,ORD0007,1098,PR074,4,23577.13,2026-08-01,Delivered
7,ORD0008,1039,PR097,4,13524.78,2026-09-18,Cancelled
8,ORD0009,1095,PR070,5,12282.50,2026-09-23,Shipped
9,ORD0010,1035,PR056,4,8502.82,2026-06-04,Cancelled
10,ORD0011,1087,PR052,2,23000.61,2026-09-16,Cancelled
11,ORD0012,1080,PR069,1,14858.54,2026-09-25,Cancelled
12,ORD0013,1085,PR004,1,3522.13,2026-08-22,Cancelled
13,ORD0014,1060,PR024,1,8284.71,2026-07-04,Cancelled
14,ORD0015,1059,PR042,3,7064.68,2026-09-06,Cancelled
15,ORD0016,1054,PR033,3,18763.25,2026-07-31,Delivered
16,ORD0017,1007,PR045,2,19563.64,2026-08-23,Delivered
17,ORD0018,1084,PR006,1,21004.84,NaT,Shipped
18,ORD0019,1080,PR020,2,16786.05,2026-06-17,Cancelled
19,ORD0020,9999,PR028,4,19207.42,2026-08-29,Pending
20,ORD0021,1022,PR078,0,19478.13,2026-09-04,Delivered
21,ORD0022,1021,PR040,1,23232.85,2026-08-14,NaN
22,ORD0023,1074,PR087,4,2038.51,2026-07-21,Shipped
23,ORD0024,1089,PR999,2,21279.79,2026-06-14,Pending
24,ORD0025,1077,PR016,5,13873.45,2026-09-09,Delivered
25,ORD0026,1055,PR085,3,464.41,2026-06-09,Pending
26,ORD0027,1054,PR063,-2,15944.29,2026-07-26,Pending
27,ORD0028,1059,PR091,2,18384.81,2026-07-26,Shipped
28,ORD0029,1084,PR035,5,11702.11,2026-09-12,Cancelled
29,ORD0030,1094,PR076,3,20793.67,2026-07-12,Shipped

In [84]:
orders['order_status'] = orders['order_status'].astype('string')

In [92]:
print(products["unit_price"].unique())

<StringArray>
[      '5846.84',       '9836.15',        '477.75',       '6005.06',
        '3521.3',       '7884.64',        '4419.3',       '9842.93',
       '1243.89',        '9004.1',       '1980.78',        '538.43',
       '4415.97',       '5246.21',       '8083.46',       '6898.89',
        '9407.6',       '7395.67',       '2049.65',       '4368.84',
       '9492.86',       '9214.63',       '6268.24',       '6666.54',
       '1332.79',       '9009.46',       '5119.51',       '6701.24',
 'not available',       '7001.36',             nan,       '1998.22',
        '6681.8',       '3852.54',       '7505.53',       '1821.87',
       '5733.14',       '4119.14',       '8352.88',       '3107.36',
       '2179.81',       '7878.01',       '6104.95',       '3289.27',
       '4472.68',       '6787.71',       '5159.62',       '7956.98',
       '9601.34',       '7385.02',       '6621.62',       '2908.49',
       '6671.15',       '6229.68',       '1023.53',        '9523.8',
        '2424.2',       '8083.97',        '1557.8',        '556.52',
       '6150.61',       '7707.04',       '4607.62',       '8871.76',
       '5798.14',       '7210.62',       '3900.39',       '4055.56',
       '1559.96',       '6906.46',       '8936.33',       '8617.36',
       '8865.11',       '7805.36',       '2265.53',       '8059.69',
       '6988.53',       '4698.04',       '5617.32',       '9181.95',
       '1300.45',       '1419.06',       '4698.97',       '5357.21',
       '3240.25',       '7575.98',       '4480.48',       '8167.56',
        '8930.0',       '9076.86',       '4513.54',       '1674.66',
        '8627.8',       '4554.69',       '7541.59',       '8413.64']
Length: 96, dtype: str

In [99]:
products["unit_price"] = products["unit_price"].replace("not available", np.nan)

In [100]:
products["unit_price"] = pd.to_numeric(products["unit_price"].astype(float))

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import os

In [4]:
print(os.listdir())

['.bash_history', '.copilot', '.git', '.git-for-windows-updater', '.gitconfig', '.idlerc', '.ipynb_checkpoints', '.ipython', '.jupyter', '.lesshst', '.ms-ad', '.python_history', '.vscode', '.vscode-shared', '1', '3D Objects', 'AppData', 'Application Data', 'Ass', 'Contacts', 'Cookies', 'customers.csv', 'Data_Cleaning_Project.ipynb', 'Desktop', 'Documents', 'Downloads', 'employee_data_cleaning_practice_200_rows.csv', 'Favorites', 'group by and merge.ipynb', 'Links', 'Local Settings', 'Music', 'My Documents', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{53b39e87-18c4-11ea-a811-000d3aa4692b}.TxR.0.regtrans-ms', 'NTUSER.DAT{53b39e87-18c4-11ea-a811-000d3aa4692b}.TxR.1.regtrans-ms', 'NTUSER.DAT{53b39e87-18c4-11ea-a811-000d3aa4692b}.TxR.2.regtrans-ms', 'NTUSER.DAT{53b39e87-18c4-11ea-a811-000d3aa4692b}.TxR.blf', 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TM.blf', 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'orders.json', 'Pictures', 'PrintHood', 'products.xlsx', 'Python', 'Python-Ass-1', 'Python-Ass-1.ipynb', 'Recent', 'Saved Games', 'Searches', 'SendTo', 'Start Menu', 'Templates', 'Untitled.ipynb', 'Untitled1.ipynb', 'Untitled2.ipynb', 'Untitled3.ipynb', 'Videos', 'WPS Cloud', 'WPS Cloud Files']

In [5]:
customers = pd.read_csv("customers.csv")

In [6]:
orders = pd.read_json("orders.json")

In [7]:
products = pd.read_excel("products.xlsx")

In [10]:
print(customers.info())

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    100 non-null    int64
 1   customer_name  100 non-null    str
 2   email          96 non-null     str
 3   city           95 non-null     str
 4   signup_date    100 non-null    datetime64[us]
dtypes: datetime64[us](1), int64(1), str(3)
memory usage: 4.0 KB
None

In [9]:
customers['signup_date'] = pd.to_datetime(customers['signup_date'], errors='coerce')

In [17]:
print(orders.info())

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      100 non-null    str
 1   customer_id   100 non-null    int64
 2   product_id    100 non-null    str
 3   quantity      94 non-null     float64
 4   order_amount  96 non-null     float64
 5   order_date    95 non-null     datetime64[us]
 6   order_status  96 non-null     string
dtypes: datetime64[us](1), float64(2), int64(1), str(2), string(1)
memory usage: 5.6 KB
None

In [12]:
orders['quantity'] = pd.to_numeric(orders['quantity'], errors='coerce')

In [13]:
orders['order_amount'] = pd.to_numeric(orders['order_amount'], errors='coerce')

In [14]:
orders["order_amount"] = orders["order_amount"].astype(float)

In [15]:
orders["order_date"] = pd.to_datetime(orders["order_date"], errors = "coerce")

In [16]:
orders['order_status'] = orders['order_status'].astype('string')

In [22]:
print(products.info())

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    100 non-null    str
 1   product_name  100 non-null    str
 2   category      100 non-null    str
 3   unit_price    94 non-null     float64
dtypes: float64(1), str(3)
memory usage: 3.3 KB
None

In [20]:
products["unit_price"] = products["unit_price"].replace("not available", np.nan)

In [21]:
products["unit_price"] = pd.to_numeric(products["unit_price"].astype(float))

In [23]:
print(customers.dtypes)

customer_id               int64
customer_name               str
email                       str
city                        str
signup_date      datetime64[us]
dtype: object

In [24]:
print(orders.dtypes)

order_id                   str
customer_id              int64
product_id                 str
quantity               float64
order_amount           float64
order_date      datetime64[us]
order_status            string
dtype: object

In [25]:
print(products.dtypes)

product_id          str
product_name        str
category            str
unit_price      float64
dtype: object

In [29]:
customers.columns = customers.columns.str.strip().str.lower().str.replace(' ' , '_')

In [30]:
orders.columns = orders.columns.str.strip().str.lower().str.replace(' ' , '_')

In [31]:
products.columns = products.columns.str.strip().str.lower().str.replace(' ' , '_')

In [32]:
customers['customer_name'] = customers['customer_name'].str.strip().str.title()

In [33]:
customers['email'] = customers['email'].str.strip().str.lower()

In [34]:
customers['city'] = customers['city'].str.strip().str.title()

In [35]:
orders['order_status'] = orders['order_status'].astype(str).str.strip().str.title()

In [36]:
products['product_name'] = products['product_name'].astype(str).str.strip().str.title()

In [37]:
products['category'] = products['category'].astype(str).str.strip().str.title()

In [39]:
customers = customers.replace(["N/A","n/a","NA","Na","Nan","None","null","not available","", "  "], np.nan)

In [40]:
orders = orders.replace(['N/A','n/a','NA','Na','Nan','None','null','Not Available','', '  '], np.nan)

In [41]:
products = products.replace(["N/A","n/a","Na","Nan","None","null","not available","", "  "], np.nan)

In [49]:
print(customers.isnull().sum())

customer_id      0
customer_name    0
email            0
city             0
signup_date      0
dtype: int64

In [61]:
print(orders.isnull().sum())

order_id        0
customer_id     0
product_id      0
quantity        0
order_amount    0
order_date      0
order_status    0
dtype: int64

In [60]:
print(products.isnull().sum())

product_id      0
product_name    0
category        0
unit_price      0
dtype: int64

In [47]:
customers["email"] = customers["email"].fillna("unknown@gmail.com")

In [48]:
customers["city"] = customers["city"].fillna("unknown")

In [51]:
orders["quantity"] = orders["quantity"].fillna(orders["quantity"].median())

In [52]:
orders["order_amount"] = orders["order_amount"].fillna(orders["order_amount"].median())

In [53]:
orders["order_date"] = orders["order_date"].fillna(orders["order_date"].mode()[0])

In [54]:
orders["order_status"] = orders["order_status"].fillna(orders["order_status"].mode()[0])

In [59]:
products["unit_price"] = products["unit_price"].fillna(products["unit_price"].median())

In [62]:
print("Customers:", customers.duplicated().sum())

Customers: 0

In [63]:
print("Orders:", orders.duplicated().sum())

Orders: 0

In [64]:
print("Products:", products.duplicated().sum())

Products: 0

In [65]:
print("customer_id unique?", customers['customer_id'].is_unique, "- duplicates:", customers['customer_id'].duplicated().sum())

customer_id unique? True - duplicates: 0

In [66]:
print("order_id unique?", orders['order_id'].is_unique, "- duplicates:", orders['order_id'].duplicated().sum())

order_id unique? True - duplicates: 0

In [67]:
print("product_id unique?", products['product_id'].is_unique, "- duplicates:", products['product_id'].duplicated().sum())

product_id unique? True - duplicates: 0

In [68]:
customers = customers.drop_duplicates()

In [69]:
orders = orders.drop_duplicates()

In [70]:
products = products.drop_duplicates()

In [71]:
bad_qty = orders[orders['quantity'] <= 0]
print("Bad quantity rows:", len(bad_qty))
print(bad_qty)

Bad quantity rows: 7
   order_id  customer_id product_id  quantity  order_amount order_date  \
20  ORD0021         1022      PR078       0.0      19478.13 2026-09-04
26  ORD0027         1054      PR063      -2.0      15944.29 2026-07-26
41  ORD0042         1095      PR062       0.0      24515.69 2026-09-01
53  ORD0054         1023      PR071      -2.0      10301.66 2026-09-04
62  ORD0063         1030      PR087       0.0      24989.37 2026-08-15
80  ORD0081         1058      PR069      -2.0      13865.15 2026-07-15
83  ORD0084         1053      PR006       0.0      17674.91 2026-09-04

   order_status
20    Delivered
26      Pending
41      Pending
53    Delivered
62    Delivered
80      Pending
83    Cancelled

In [72]:
bad_amount = orders[orders['order_amount'] < 0]
print("\nBad amount rows:", len(bad_amount))
print(bad_amount)

Bad amount rows: 3
   order_id  customer_id product_id  quantity  order_amount order_date  \
31  ORD0032         1086      PR049       3.0        -500.0 2026-06-04
63  ORD0064         1087      PR035       3.0        -500.0 2026-06-06
95  ORD0096         1031      PR999       3.0        -500.0 2026-06-19

   order_status
31    Cancelled
63      Shipped
95      Shipped

In [73]:
orders['flag_review'] = 'ok'
orders.loc[orders['quantity'] <= 0, 'flag_review'] = 'bad quantity'
orders.loc[orders['order_amount'] < 0, 'flag_review'] = 'bad amount'

In [74]:
merged = orders.merge(customers, on='customer_id', how='left')

In [77]:
print(merged.head())

  order_id  customer_id product_id  quantity  order_amount order_date  \
0  ORD0001         1036      PR099       5.0       6973.75 2026-08-02
1  ORD0002         1010      PR092       3.0       8495.81 2026-07-01
2  ORD0003         1070      PR011       2.0       9668.43 2026-06-20
3  ORD0004         1020      PR091       2.0      10278.84 2026-06-09
4  ORD0005         1070      PR060       4.0      20847.35 2026-06-08

  order_status flag_review customer_name                       email  \
0      Shipped          ok   Nisha Kumar   nisha.kumar36@example.com
1      Pending          ok  Ananya Gupta  ananya.gupta10@example.com
2      Shipped          ok   Sana Pillai   sana.pillai70@example.com
3    Cancelled          ok   Ravi Joseph   ravi.joseph20@example.com
4      Shipped          ok   Sana Pillai   sana.pillai70@example.com

        city signup_date
0  Bengaluru  2026-07-05
1      Delhi  2026-01-23
2      Kochi  2026-05-14
3    Chennai  2026-06-11
4      Kochi  2026-05-14

In [79]:
print(merged.shape)

(100, 12)

In [83]:
final_merged = pd.merge(merged, products, on='product_id', how='left')

In [84]:
print(final_merged.shape)

(100, 15)

In [85]:
print(final_merged.head())

  order_id  customer_id product_id  quantity  order_amount order_date  \
0  ORD0001         1036      PR099       5.0       6973.75 2026-08-02
1  ORD0002         1010      PR092       3.0       8495.81 2026-07-01
2  ORD0003         1070      PR011       2.0       9668.43 2026-06-20
3  ORD0004         1020      PR091       2.0      10278.84 2026-06-09
4  ORD0005         1070      PR060       4.0      20847.35 2026-06-08

  order_status flag_review customer_name                       email  \
0      Shipped          ok   Nisha Kumar   nisha.kumar36@example.com
1      Pending          ok  Ananya Gupta  ananya.gupta10@example.com
2      Shipped          ok   Sana Pillai   sana.pillai70@example.com
3    Cancelled          ok   Ravi Joseph   ravi.joseph20@example.com
4      Shipped          ok   Sana Pillai   sana.pillai70@example.com

        city signup_date          product_name     category  unit_price
0  Bengaluru  2026-07-05       Pen Set Model 5   Stationery     7541.59
1      Delhi  2026-01-23       Monitor Model 5  Electronics     8930.00
2      Kochi  2026-05-14          Notebook Set   Stationery     1980.78
3    Chennai  2026-06-11  Notebook Set Model 5   Stationery     8167.56
4      Kochi  2026-05-14    Travel Mug Model 3    Lifestyle     1557.80

In [86]:
print(final_merged.columns.tolist())

['order_id', 'customer_id', 'product_id', 'quantity', 'order_amount', 'order_date', 'order_status', 'flag_review', 'customer_name', 'email', 'city', 'signup_date', 'product_name', 'category', 'unit_price']

In [87]:
Data_Cleaned_Project = final_merged

In [88]:
print(Data_Cleaned_Project.shape)

(100, 15)

In [89]:
print(Data_Cleaned_Project.head())

  order_id  customer_id product_id  quantity  order_amount order_date  \
0  ORD0001         1036      PR099       5.0       6973.75 2026-08-02
1  ORD0002         1010      PR092       3.0       8495.81 2026-07-01
2  ORD0003         1070      PR011       2.0       9668.43 2026-06-20
3  ORD0004         1020      PR091       2.0      10278.84 2026-06-09
4  ORD0005         1070      PR060       4.0      20847.35 2026-06-08

  order_status flag_review customer_name                       email  \
0      Shipped          ok   Nisha Kumar   nisha.kumar36@example.com
1      Pending          ok  Ananya Gupta  ananya.gupta10@example.com
2      Shipped          ok   Sana Pillai   sana.pillai70@example.com
3    Cancelled          ok   Ravi Joseph   ravi.joseph20@example.com
4      Shipped          ok   Sana Pillai   sana.pillai70@example.com

        city signup_date          product_name     category  unit_price
0  Bengaluru  2026-07-05       Pen Set Model 5   Stationery     7541.59
1      Delhi  2026-01-23       Monitor Model 5  Electronics     8930.00
2      Kochi  2026-05-14          Notebook Set   Stationery     1980.78
3    Chennai  2026-06-11  Notebook Set Model 5   Stationery     8167.56
4      Kochi  2026-05-14    Travel Mug Model 3    Lifestyle     1557.80

In [90]:
unmatched_customers = Data_Cleaned_Project[Data_Cleaned_Project['customer_name'].isna()]

In [91]:
unmatched_products = Data_Cleaned_Project[Data_Cleaned_Project['product_name'].isna()]

In [92]:
flagged = Data_Cleaned_Project[Data_Cleaned_Project['flag_review']!='ok']

In [93]:
Data_Cleaned_Project.to_csv('cleaned_merged_orders.csv', index=False)

In [94]:
Data_Cleaned_Project.to_excel('cleaned_merged_orders.xlsx', index=False)

In [95]:
import pandas as pd

In [96]:
# 1. Count missing values
missing_report = Data_Cleaned_Project.isnull().sum().to_frame('missing_count')
print("Missing values:")
print(missing_report)

Missing values:
               missing_count
order_id                   0
customer_id                0
product_id                 0
quantity                   0
order_amount               0
order_date                 0
order_status               0
flag_review                0
customer_name              5
email                      5
city                       5
signup_date                5
product_name               4
category                   4
unit_price                 4

In [97]:
# 2. Unmatched products (product not found)
unmatched_products = Data_Cleaned_Project[Data_Cleaned_Project['product_name'].isna()]

In [98]:
# 3. Flagged for review
flagged_review = Data_Cleaned_Project[Data_Cleaned_Project['flag_review'] != 'ok']

In [99]:
# 4. Report Excel
with pd.ExcelWriter('data_quality_report.xlsx') as writer:
    missing_report.to_excel(writer, sheet_name='missing_values')
    unmatched_products.to_excel(writer, sheet_name='unmatched_products', index=False)
    flagged_review.to_excel(writer, sheet_name='flagged_review', index=False)
    Data_Cleaned_Project.head(100).to_excel(writer, sheet_name='sample_final_data', index=False)

In [100]:
print("\nDONE! Report created: data_quality_report.xlsx")
print(f"Unmatched products: {len(unmatched_products)}")
print(f"Flagged reviews: {len(flagged_review)}")
print(f"Final shape: {Data_Cleaned_Project.shape}")

DONE! Report created: data_quality_report.xlsx
Unmatched products: 4
Flagged reviews: 10
Final shape: (100, 15)

In [31]:
# Q13
print("Matching customers:", len(Data_Cleaned_Project.dropna(subset=['customer_name'])))

Matching customers: 95

In [32]:
#Q 14
print("Matching products:", len(Data_Cleaned_Project.dropna(subset=['product_name'])))

Matching products: 96

In [2]:
import pandas as pd

In [3]:
Data_Cleaned_Project = pd.read_excel("cleaned_merged_orders.xlsx")

In [6]:
# Q15
city_orders = Data_Cleaned_Project['city'].value_counts()
print(city_orders)

city
Delhi        15
Hyderabad    13
Mumbai       13
Chennai      12
Bengaluru    11
Kolkata      11
Kochi        10
Pune          8
unknown       2
Name: count, dtype: int64

In [33]:
city_orders = Data_Cleaned_Project['city'].value_counts()
print(city_orders.head(1))

city
Delhi    15
Name: count, dtype: int64

In [5]:
print(Data_Cleaned_Project.columns.tolist())

['order_id', 'customer_id', 'product_id', 'quantity', 'order_amount', 'order_date', 'order_status', 'flag_review', 'customer_name', 'email', 'city', 'signup_date', 'product_name', 'category', 'unit_price']

In [30]:
# Q16
valid_orders = Data_Cleaned_Project[Data_Cleaned_Project['order_amount'] > 0]
total_amount = valid_orders['order_amount'].sum()

print("Total order_amount:", total_amount)

Total order_amount: 1311034.24

In [11]:
#Q 17
category_count = Data_Cleaned_Project['category'].value_counts()
print(category_count)

category
Electronics    32
Lifestyle      15
Home           14
Stationery     13
Furniture      11
Accessories    11
Name: count, dtype: int64

In [13]:
category_count = Data_Cleaned_Project['category'].value_counts()
print(category_count.head(1))

category
Electronics    32
Name: count, dtype: int64

In [14]:
#Q 18
non_numeric = 0
zero_negative = 0

for value in Data_Cleaned_Project['quantity']:
    try:
        if float(value) <= 0:
            zero_negative += 1
    except:
        non_numeric += 1

print("Non-numeric:", non_numeric)
print("Zero or negative:", zero_negative)
print("Total:", non_numeric + zero_negative)

Non-numeric: 0
Zero or negative: 7
Total: 7

In [15]:
#Q 19
missing = 0
invalid = 0

for price in Data_Cleaned_Project['unit_price']:
    try:
        if float(price) <= 0:
            invalid += 1
    except:
        missing += 1

print("Missing (blank/text):", missing)
print("Invalid (zero/negative):", invalid)
print("Total missing or invalid:", missing + invalid)

Missing (blank/text): 0
Invalid (zero/negative): 0
Total missing or invalid: 0

In [19]:
#Q 20
orders = pd.read_excel('cleaned_merged_orders.xlsx')
customers = pd.read_csv('customers.csv')
products = pd.read_excel('products.xlsx')

unmatched_customers = orders[~orders['customer_id'].isin(customers['customer_id'])]
unmatched_products = orders[~orders['product_id'].isin(products['product_id'])]

print("Orders with unmatched customer IDs:", len(unmatched_customers))
print(unmatched_customers)

print("\nOrders with unmatched product IDs:", len(unmatched_products))
print(unmatched_products)

Orders with unmatched customer IDs: 5
   order_id  customer_id product_id  quantity  order_amount order_date  \
19  ORD0020         9999      PR028         4     19207.420 2026-08-29
39  ORD0040         9999      PR040         3     18073.920 2026-06-30
59  ORD0060         9999      PR089         3     23575.500 2026-08-29
79  ORD0080         9999      PR076         3     21651.730 2026-08-24
99  ORD0100         9999      PR039         2     13773.765 2026-07-20

   order_status flag_review customer_name email city signup_date  \
19      Pending          ok           NaN   NaN  NaN         NaT
39    Delivered          ok           NaN   NaN  NaN         NaT
59    Cancelled          ok           NaN   NaN  NaN         NaT
79    Cancelled          ok           NaN   NaN  NaN         NaT
99    Cancelled          ok           NaN   NaN  NaN         NaT

            product_name     category  unit_price
19  Laptop Stand Model 2  Accessories     6701.24
39    Travel Mug Model 2    Lifestyle     3107.36
59  Water Bottle Model 5    Lifestyle     7575.98
79     Table Fan Model 4         Home     7805.36
99       Pen Set Model 2   Stationery     8352.88

Orders with unmatched product IDs: 4
   order_id  customer_id product_id  quantity  order_amount order_date  \
23  ORD0024         1089      PR999         2      21279.79 2026-06-14
47  ORD0048         1009      PR999         3       3920.42 2026-06-10
71  ORD0072         1098      PR999         2      23202.67 2026-09-04
95  ORD0096         1031      PR999         3       -500.00 2026-06-19

   order_status flag_review  customer_name                        email  \
23      Pending          ok  Priya Shankar  priya.shankar89@example.com
47    Delivered          ok    Meena Verma     meena.verma9@example.com
71      Shipped          ok    Karthik Rao    karthik.rao98@example.com
95      Shipped  bad amount      Isha Iyer      isha.iyer31@example.com

         city signup_date product_name category  unit_price
23      Delhi  2026-07-06          NaN      NaN         NaN
47  Bengaluru  2026-07-03          NaN      NaN         NaN
71      Delhi  2026-02-05          NaN      NaN         NaN
95      Kochi  2026-02-27          NaN      NaN         NaN

In [20]:
print("Total orders with unmatched customer IDs: 5")
print("Total orders with unmatched product IDs: 4")

Total orders with unmatched customer IDs: 5
Total orders with unmatched product IDs: 4

In [24]:
# Q21
# BEFORE FILES
customers = pd.read_csv('customers.csv')
orders = pd.read_json('orders.json') 
products = pd.read_excel('products.xlsx')

# AFTER FILE 
after = pd.read_excel('cleaned_merged_orders.xlsx')

print("BEFORE CLEANING")
print("\n1. Missing in customers.csv:")
print(customers.isna().sum())
print("Total missing:", customers.isna().sum().sum())

print("\n2. Missing in orders.json:")
print(orders.isna().sum())
print("Total missing:", orders.isna().sum().sum())

print("\n3. Missing in products.xlsx:")
print(products.isna().sum())
print("Total missing:", products.isna().sum().sum())

print("\n AFTER CLEANING AND MERGING ")
print("\nMissing in cleaned_merged_orders.xlsx:")
print(after.isna().sum())
print("Total missing:", after.isna().sum().sum())

BEFORE CLEANING

1. Missing in customers.csv:
customer_id      0
customer_name    0
email            4
city             5
signup_date      0
dtype: int64
Total missing: 9

2. Missing in orders.json:
order_id        0
customer_id     0
product_id      0
quantity        0
order_amount    0
order_date      0
order_status    4
dtype: int64
Total missing: 4

3. Missing in products.xlsx:
product_id      0
product_name    0
category        0
unit_price      3
dtype: int64
Total missing: 3

 AFTER CLEANING AND MERGING

Missing in cleaned_merged_orders.xlsx:
order_id         0
customer_id      0
product_id       0
quantity         0
order_amount     0
order_date       0
order_status     0
flag_review      0
customer_name    5
email            5
city             5
signup_date      5
product_name     4
category         4
unit_price       4
dtype: int64
Total missing: 32

In [22]:
final = pd.read_excel('cleaned_merged_orders.xlsx')

total_rows = len(final)
print("Total rows in final output:", total_rows)

flagged = final[final['flag_review'] != 'ok']
print("Records flagged for review:", len(flagged))

print("\nFlag details:")
print(final['flag_review'].value_counts())

print("\nFlagged records:")
print(flagged[['order_id', 'flag_review']])

Total rows in final output: 100
Records flagged for review: 10

Flag details:
flag_review
ok              90
bad quantity     7
bad amount       3
Name: count, dtype: int64

Flagged records:
   order_id   flag_review
20  ORD0021  bad quantity
26  ORD0027  bad quantity
31  ORD0032    bad amount
41  ORD0042  bad quantity
53  ORD0054  bad quantity
62  ORD0063  bad quantity
63  ORD0064    bad amount
80  ORD0081  bad quantity
83  ORD0084  bad quantity
95  ORD0096    bad amount

In [23]:
# Q22
final = pd.read_excel('cleaned_merged_orders.xlsx')

count = 0
flag_count = 0

for flag in final['flag_review']:
    count += 1
    if flag != 'ok':
        flag_count += 1

print("Total rows:", count)
print("Flagged for review:", flag_count)

Total rows: 100
Flagged for review: 10

In [29]:
final_merged = pd.read_excel('cleaned_merged_orders.xlsx')
final_merged.columns = final_merged.columns.str.title()
print(final_merged.columns.tolist())

['Order_Id', 'Customer_Id', 'Product_Id', 'Quantity', 'Order_Amount', 'Order_Date', 'Order_Status', 'Flag_Review', 'Customer_Name', 'Email', 'City', 'Signup_Date', 'Product_Name', 'Category', 'Unit_Price']

In [34]:
import pandas as pd

final = pd.read_excel('cleaned_merged_orders.xlsx')